server:
  port: 0

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      instanceCount: 3
      bindings:
        #output:
          #destination: fastpasstollstatus
        input:
          destination: fastpasstoll
          group: tollProcessingGroup
          consumer:
            partitioned: true
