server:
  port: 9191

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.int}

ribbon:
  eureka:
    enabled: true

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
      stream:
        default:
          contentType: application/json
        bindings:
          fastpassTollChannel:
            destination: fastpasstoll
            producer:
              partitionKeyExpression: payload.stationid
              partitionCount: 3

PLURALSIGHT-FASTPASS-INSTANCE:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
    #listOfServers: http://localhost:52928,http://localhosta:52880
    #MaxAutoRetries: 0
    #OkToRetryOnAllOperations: false
    #MaxAutoRetriesNextServer: 1
